
'use strict';
(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const assets=JSON.parse($('#asset-map').textContent);const reduce=matchMedia('(prefers-reduced-motion: reduce)');
const projects={
'nightsky':{title:'Nightsky',category:'A brand, from the beginning.',services:'Naming, visual identity, packaging and positioning.',story:'CM&A developed Nightsky Gin n’ Tonic from the first idea: the brand name, visual identity, packaging and “Give Me The Night” line. A ready-to-drink brand made for a new generation of Zimbabwean consumers.',images:[['nightsky-poster','Nightsky campaign poster'],['nightsky-cherry','Nightsky Cherry packaging'],['nightsky-lime','Nightsky Lime packaging'],['nightsky-ale','Nightsky Ale packaging']]},
'hunters':{title:'Hunter’s Big Refresh',category:'A promotion with a national stage.',services:'Campaign concept, promotion and activation.',story:'A nationwide Hunter’s Cider promotion, conceived and executed by CM&A. The campaign brought together promotional communication and consumer rewards, including trips to Zanzibar, PlayStation 5 consoles and smartphones.',images:[['hunters','Hunter’s Big Refresh campaign artwork'],['hunters-event','Hunter’s campaign activation'],['hunters-social','Hunter’s campaign communication']]},
'gold-blend':{title:'Gold Blend',category:'A familiar name. A new chapter.',services:'Brand evolution, packaging and positioning.',story:'An evolution of a homegrown Zimbabwean whisky brand. CM&A updated packaging across the range and developed the positioning “Mix In The Right Circles, With The Right Blend”, connecting quality, friendship and responsible enjoyment.',images:[['gold-poster','Gold Blend campaign poster'],['gold-black','Gold Blend Black packaging'],['gold-nine','Gold Blend No. 9 packaging'],['gold-event','Gold Blend launch event']]},
'whitestone':{title:'Whitestone',category:'It’s all about taste.',services:'Brand strategy, visual identity and packaging.',story:'A complete visual and strategic rebrand for Whitestone Gin. CM&A developed its new identity, packaging and “It’s All About Taste” positioning.',images:[['whitestone','Whitestone Gin packaging'],['whitestone-one','Whitestone Gin bottle design'],['whitestone-two','Whitestone Gin range']]},
'land-of-gold':{title:'Land of Gold',category:'Rewarding loyalty, nationwide.',services:'Promotion concept and campaign management.',story:'CM&A conceptualised and managed Gold Blend’s nationwide Land of Gold promotion. The consumer campaign centred on the opportunity to win a residential stand.',images:[['land-of-gold','Still from the supplied Land of Gold promotion film'],['gold-standard','Gold Blend standard whisky']]},
'elegance':{title:'Elegance',category:'Everyday care, reconsidered.',services:'Brand evolution and packaging design.',story:'A contemporary look for the Elegance range of petroleum jellies, lotions, creams and shower gels. CM&A developed packaging across the range, alongside product packaging for Dr Klin bathroom cleaners and Maxi-Smooth Camphor Creams.',images:[['elegance','Elegance Cocoa body cream'],['elegance-aloe','Elegance Aloe Vera lotion'],['elegance-cocoa','Elegance Cocoa lotion'],['elegance-pink','Elegance aqueous cream'],['dr-klin','Dr Klin product packaging']]}
};
const caseDialog=$('#case-dialog'),menu=$('#menu-dialog'),privacy=$('#privacy-dialog');let returnFocus=null,lastSection='#work';
function syncLock(){document.body.classList.toggle('locked',!!$('dialog[open]'));}
function showProject(key,trigger){const p=projects[key];if(!p)return;returnFocus=trigger||document.activeElement;$('#case-title').textContent=p.title;$('#case-category').textContent=p.category;$('#case-services').textContent=p.services;$('#case-story').textContent=p.story;const gallery=$('#case-gallery');gallery.replaceChildren();for(const [key,alt]of p.images){if(!assets[key])continue;const figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=assets[key];img.alt=alt;img.decoding='async';caption.textContent=alt;figure.append(img,caption);gallery.append(figure);}if(!caseDialog.open)caseDialog.showModal();caseDialog.scrollTop=0;syncLock();$('#case-close').focus();}
function closeProject(update=true){const wasOpen=caseDialog.open;if(wasOpen)caseDialog.close();if(update&&location.hash.startsWith('#project/'))history.replaceState(null,'',lastSection);syncLock();if(wasOpen&&update&&returnFocus&&returnFocus.isConnected)returnFocus.focus({preventScroll:true});}
document.addEventListener('click',e=>{const target=e.target.closest('[data-project]');if(!target)return;e.preventDefault();lastSection=location.hash&&!location.hash.startsWith('#project/')?location.hash:'#work';const key=target.dataset.project;history.pushState(null,'','#project/'+key);showProject(key,target);});
$('#case-close').addEventListener('click',()=>closeProject());caseDialog.addEventListener('cancel',e=>{e.preventDefault();closeProject();});caseDialog.addEventListener('click',e=>{if(e.target===caseDialog){const r=caseDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeProject();}});$('#case-contact').addEventListener('click',()=>closeProject(false));
function closeMenu(){if(menu.open)menu.close();$('#menu-open').setAttribute('aria-expanded','false');syncLock();}
$('#menu-open').addEventListener('click',()=>{menu.showModal();$('#menu-open').setAttribute('aria-expanded','true');syncLock();$('#menu-close').focus();});$('#menu-close').addEventListener('click',closeMenu);menu.addEventListener('close',closeMenu);menu.addEventListener('cancel',e=>{e.preventDefault();closeMenu();});$$('a',menu).forEach(a=>a.addEventListener('click',closeMenu));window.addEventListener('resize',()=>{if(innerWidth>760)closeMenu();});
$('#privacy-open').addEventListener('click',()=>{privacy.showModal();syncLock();});$('#privacy-close').addEventListener('click',()=>{privacy.close();syncLock();});privacy.addEventListener('close',syncLock);privacy.addEventListener('cancel',e=>{e.preventDefault();privacy.close();syncLock();});caseDialog.addEventListener('close',syncLock);
function route(){if(location.hash.startsWith('#project/')){showProject(location.hash.slice(9));}else{closeProject(false);if(location.hash==='#about'||location.hash==='#brands'){history.replaceState(null,'','#studio');$('#studio').scrollIntoView();}}}addEventListener('popstate',route);addEventListener('hashchange',route);
const slides=[{name:'Nightsky',key:'nightsky',description:'A name. An identity. A night to remember.',color:'#e8edbe',images:['nightsky-cherry','nightsky-lime','nightsky-ale'],alts:['Nightsky Cherry packaging','Nightsky Lime packaging','Nightsky Ale packaging']},{name:'Gold Blend',key:'gold-blend',description:'A familiar name. A new chapter.',color:'#ebd1ac',images:['gold-standard','gold-black','gold-nine'],alts:['Gold Blend standard whisky','Gold Blend Black packaging','Gold Blend No. 9 packaging']},{name:'Whitestone',key:'whitestone',description:'A fresh identity. It’s all about taste.',color:'#d4e1df',images:['whitestone-one','whitestone','whitestone-two'],alts:['Whitestone Gin bottle','Whitestone Gin packaging','Whitestone Gin range']}];
let slide=0,paused=reduce.matches,hover=false,focus=false,visible=true,busy=false,revision=0;const scene=$('#scene'),art=$('#scene-art');let due=performance.now()+6000;
function pauseUI(){$('#pause').setAttribute('aria-pressed',String(paused));$('#pause').setAttribute('aria-label',paused?'Play automatic rotation':'Pause automatic rotation');$('#pause-icon').setAttribute('href',paused?'#icon-play':'#icon-pause');}
async function changeSlide(index,manual=false){const myRev=++revision;slide=(index+slides.length)%slides.length;const s=slides[slide];due=performance.now()+6000;busy=true;const nodes=s.images.map((key,i)=>{const image=new Image();image.src=assets[key];image.alt=s.alts[i];image.width=450;image.height=1100;return image;});await Promise.all(nodes.map(i=>i.decode?i.decode().catch(()=>{}):Promise.resolve()));if(myRev!==revision)return;art.classList.add('changing');if(!reduce.matches)await new Promise(r=>setTimeout(r,150));if(myRev!==revision)return;art.replaceChildren(...nodes);scene.style.background=s.color;$('#scene-name').textContent=s.name;$('#scene-description').textContent=s.description;$('#scene-project').dataset.project=s.key;$('#scene-counter').textContent=String(slide+1).padStart(2,'0')+' / 03';$$('[data-slide]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.slide===slide)));requestAnimationFrame(()=>art.classList.remove('changing'));if(manual)$('#slide-status').textContent=s.name+' project selected';busy=false;}
$('#next').addEventListener('click',()=>changeSlide(slide+1,true));$('#prev').addEventListener('click',()=>changeSlide(slide-1,true));$$('[data-slide]').forEach(b=>b.addEventListener('click',()=>changeSlide(+b.dataset.slide,true)));$('#pause').addEventListener('click',()=>{paused=!paused;due=performance.now()+6000;pauseUI();});scene.addEventListener('mouseenter',()=>{hover=true;});scene.addEventListener('mouseleave',()=>{hover=false;due=performance.now()+6000;});scene.addEventListener('focusin',()=>{focus=true;});scene.addEventListener('focusout',e=>{focus=scene.contains(e.relatedTarget);due=performance.now()+6000;});scene.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();changeSlide(slide+(e.key==='ArrowRight'?1:-1),true);}});let touchX=0,touchY=0;scene.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY;},{passive:true});scene.addEventListener('touchend',e=>{let x=e.changedTouches[0].clientX-touchX,y=e.changedTouches[0].clientY-touchY;if(Math.abs(x)>55&&Math.abs(x)>Math.abs(y)*1.5)changeSlide(slide+(x<0?1:-1),true);},{passive:true});new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;due=performance.now()+6000;},{threshold:.25}).observe(scene);document.addEventListener('visibilitychange',()=>{due=performance.now()+6000;});reduce.addEventListener('change',()=>{if(reduce.matches)paused=true;pauseUI();});setInterval(()=>{if(!paused&&!hover&&!focus&&visible&&!document.hidden&&!$('dialog[open]')&&!busy&&performance.now()>due)changeSlide(slide+1);},250);pauseUI();
const sections=['work','studio','services','contact'].map(id=>$('#'+id));let scrollPending=false;function track(){scrollPending=false;let active='';const marker=$('.header').getBoundingClientRect().height+innerHeight*.25;for(const sec of sections)if(sec.getBoundingClientRect().top<=marker)active=sec.id;if(scrollY+innerHeight>=document.documentElement.scrollHeight-12)active='contact';$$('.nav-links a,.menu-list a').forEach(a=>{const on=a.hash==='#'+active;a.classList.toggle('active',on);if(on)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}function scheduleTrack(){if(!scrollPending){scrollPending=true;requestAnimationFrame(track);}}addEventListener('scroll',scheduleTrack,{passive:true});addEventListener('resize',scheduleTrack);new ResizeObserver(scheduleTrack).observe(document.body);$$('.service').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)$$('.service').forEach(other=>{if(other!==d)other.open=false;});scheduleTrack();}));
$('#enquiry-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;const data=new FormData(f);const text='Hello CM&A,\n\n'+data.get('message')+'\n\nName: '+data.get('name')+'\nEmail: '+data.get('email')+'\nCompany: '+(data.get('company')||'Not specified')+'\nService: '+data.get('service');$('#enquiry-copy').value=text;$('#open-email').href='mailto:tendayi@cma.co.zw?subject='+encodeURIComponent('Project enquiry: '+data.get('service'))+'&body='+encodeURIComponent(text);$('#enquiry-ready').hidden=false;$('#enquiry-status').textContent='Your enquiry is ready. Nothing has been sent.';$('#enquiry-ready').scrollIntoView({behavior:reduce.matches?'auto':'smooth',block:'nearest'});});$('#copy-enquiry').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#enquiry-copy').value);$('#enquiry-status').textContent='Copied. Paste the message into an email to tendayi@cma.co.zw.';}catch{$('#enquiry-copy').focus();$('#enquiry-copy').select();$('#enquiry-status').textContent='Select and copy the message, then email tendayi@cma.co.zw.';}});
route();track();
})();
